repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: ^tests/test_data
    -   id: end-of-file-fixer
        exclude: ^tests/test_data
    -   id: trailing-whitespace
        exclude: ^tests/test_data
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        exclude: ^tests/test_data/*
        language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    -   id: mypy
